name: HTML Lint
on:
  push:
    branches: [ "main" ]
  pull_request:
jobs:
  tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tidy
        run: sudo apt-get update && sudo apt-get install -y tidy
      - name: Lint index.html
        run: tidy -qe index.html || true
